window.onload = function() {
	const splashes = [
		"Hydrogen Peroxyde",
		"fjdksla;",
		"Civil Disobedience",
		"ur mom",
		"The product of intelligence",
		"Wake up!",
		"*default dance*",
		"Learn the ABCs",
		"Billy Bounce Murderer",
		"Insert Cheeky Meme Here",
		"The Battle Dogs",
		"Orange <3 Purple",
		"Orange <3 Pink & Teal",
		"Super Sneaky Coded Message",
		"Psst, up here!",
		"Kid, I got a van in my candy.",
		"javascript:void(0);",
		"Change my mind!",
		"r/ihavereddit",
		"Dexie is cool",
		"Ragequit",
		"Squidd Kiddniac didn't endorse it!",
		"Insert biased opinion here",
		"Can we just stop now",
		"Thank you, Ross. Very cool!",
		"It's your, not you are",
		"Get your facts right",
		"Get your facts uncensored",
		"Uncensored squid stuff",
		"Line 32, column 26",
		"It's not Tor!",
		"Four point nine stars",
		"Uh oh, stinky!",
		"Me + Chicken Nuggets",
		"'Till the very end",
		"No sweat, let's floss",
		"Unhappy Rancher",
		"Sploosh",
		"Beep Beep Lechuga",
		"C6H8O6",
		"Depressed Pistol",
		"Solo cups, Duo cups",
		"[object Object]",
		"Can I get a uhhhhhhhhhhhhhhhhh",
		"NodeJS > Django > Rails",
		"The Terminal-tor",
		"inb4 school blocks it",
		"Lucky you! This splash is cool!",
		"Bruh process started succesfully",
		"Bruh commencing momentarily",
		"Bruh moment",
		"Half of my script is splashed",
		"Outdated Java",
		"JS > Py > Java > C++ > C > Ruby",
		"placeholder",
		"k__t__w__A",
		"Glubfub was here",
		"Line $cobol_age",
		"Silk Road",
		"Not exactly dark, but web",
		"Made in Science class!",
		"Come on, I was bored!",
		"I'm getting tired of this",
		"Immature!",
		"I've hacked into the mainframe",
		"jolly |R|anc|H|ers are |COOL|",
		"sbeve",
		"frinds r lik snofleks",
		"Hydroflask Peroxyde",
		"VSCO HTML be like",
		"This text changes on refresh!",
		"FBI is watching...",
		"El Pollo y La Leche",
		"CodeGolf",
		"Google Search",
		"Spoofy",
		"Taco Time",
		"you're invited to my taco tuesday",
		"Voodoo steals game ideas!",
		"Microtransactions",
		"Yeah!",
		"Bnbajoh Dpef@",
		"NodeJS Piggy",
		"Remember LambGame64?",
		"let DexieTheSheep = Lamby777;",
		"local oof = Instance.new(\"Part\", workspace)",
		"Peppa, why are you in my JS?",
		"let YouTube = new GreedyBoi();",
		"No signup, No BS",
		"Imagine working haha",
		"Not my fault",
		"Not my problem",
		"And disabled their algorithms",
		"Cool Kids Only",
		"Yo guys it's Dhaar Maannn",
		"bep bep lechiga",
		"The Terrarian",
		"I wAnT bLuE tOaD",
		"splish splash",
		"your opinion's a splash",
		"rb.dexie.codes",
	];
	if (document.title == ".")
	document.title = splashes[Math.floor(Math.random() * splashes.length)];
	const emojiNames = [
		{name: "oof", file: "oof.png", desc: "Roblox Oof Face", size: 1},
	];
	for (emoji of emojiNames) {
		document.body.innerHTML = document.body.innerHTML.replace(new RegExp(
			`\\|:\\s?${emoji.name}\\s?:\\|`, "g"), '<img src="img/' + emoji.file + 
			'" width="' + (emoji.size * 24) + '" alt-text=' + emoji.desc + 
			' title="bruh moment"/>');
	}
}